### ISSUE TITLE
Use single template for many languages

### ISSUE THREAD

**Issue by webian** [Gregor-Agnes/newsletter_subscribe#1]
Hi,
I'm trying this extension and found that there's one template folder for each language.
Isn't possible to have a single template and use instead `<f:translate>` for the localization?

**Comment by Gregor-Agnes** [comment]
Sorry for late reply.
Not possible at the moment. I thought it would be easier to create the email-templates for each language separately because the dialogue differs a lot. For example it's not possible to change the order of the elements for each language, if there is only one template for all.
Maybe I will add that option in a later release.
